### ISSUE TITLE
Bug in AuthenticatorBuilder.java

### ISSUE THREAD

**Issue by omaass** [Adobe-Marketing-Cloud/analytics-java-library#11]
There seems to be a copy-and-paste bug in AuthenticatorBuilder.java:
All setter methods check for internal variable "type" instead of the given method parameter. E.g.

``` java
    public AuthenticatorBuilder setProxy(Proxy proxy) {
        if (type == null) {
            throw new NullPointerException("Proxy can't be null");
        }
        this.proxy = proxy;
        return this;
    }
```

This leads to NullPointerExceptions when type is not yet set. 
Locally I changed all the setter methods to check the params instead, e.g.

``` java
    public AuthenticatorBuilder setProxy(Proxy proxy) {
        if (proxy == null) {
            throw new NullPointerException("Proxy can't be null");
        }
        [...]
```

Additionally I had to change the constructor of AnalyticsClientBuilder to use `Proxy.NO_PROXY` instead of `new Proxy(Type.DIRECT, null)` because that would throw an IllegalArgumentException in `java.net.Proxy`

**Comment by trekawek** [comment]
Fixed in c70c2ca6dd59e1ff417c10e038e154937eb27c17.
