### ISSUE TITLE
Empty export section of bundle

### ISSUE THREAD

**Issue by cylinder-y** [Adobe-Marketing-Cloud/analytics-java-library#15]
There is bundle in  [ maven repository ](https://mvnrepository.com/artifact/com.adobe.granite.analytics/java-client/1.1), and it's export section is empty.

At this moment, to make analytics OSGi bundle work correctly it is necessary to fix manifest file manually

**Comment by henrykuijpers** [comment]
The error is that the `<Export-Package>` in the pom.xml exports `com.adobe.analytics.client*` instead of `com.adobe.**granite**.analytics.client*`
