### ISSUE TITLE
Make sure library is uploaded to maven.org

### ISSUE THREAD

**Issue by michael-mccutcheon** [Adobe-Marketing-Cloud/analytics-java-library#21]
When I use the XML you have for the POM file, it can't find this library in Maven.

Searching maven.org returns no results either.

If you could ensure this library was in Maven that would be appreciated :)

**Comment by cydeni** [comment]
did you include the stuff for the repository section?
if not, check the pom.xml of this project

**Comment by trekawek** [comment]
As @denibode wrote. I updated the README.md and linked the [Adobe Public Maven Repo](https://repo.adobe.com/).
