### ISSUE TITLE
JWT Auth does not work

### ISSUE THREAD

**Issue by ghost** [Adobe-Marketing-Cloud/analytics-java-library#6]
JWT Auth does not work because the token request is made with a GET request while the endpoint only accepts POST with POST parameter similar to the client credentials auth that i've written.

**Comment by trekawek** [comment]
Thanks for the bug reports! I fixed reported issues in a separate branch `bug-friday`. Could you take a look and give some feedback?

**Comment by ghost** [comment]
Changes seem good! It think it might actually work now but i got to test it and i'll come back to you

**Comment by ghost** [comment]
Stil the same issue with your library and osgi
keeps complaining about android.util package not being present and bouncy castle, i really suggest replacing the jjwt library

**Comment by kkozlowska** [comment]
Hello! The bundle should install on AEM instance properly right now - there was a difference in the required and provided version of commons-codec dependency. 

However when I was testing the implementation I experienced several different errors connected with required "iss" and "sub" information sent together with JWT token. Are there any restriction on the API side regarding these values?

**Comment by iousin** [comment]
Hi Guys, 
Assuming branch bug-friday is working. Will it be possible to merge into master. I'm using this api in a new project and had to fix some code on the local master copy which I think is already fixed by bug-friday branch. 

https://github.com/Adobe-Marketing-Cloud/analytics-java-library/tree/bug-friday

Thanks.

**Comment by trekawek** [comment]
It seems the JWT problem is fixed, closing the issue.
