### ISSUE TITLE
Proxy support bug

### ISSUE THREAD

**Issue by ghost** [Adobe-Marketing-Cloud/analytics-java-library#8]
1. Working without proxy does not longer work, this switch should be added everywhere:
   if (proxy != null) {
           connection = (HttpURLConnection) url.openConnection(proxy);
       }else {
           connection = (HttpURLConnection) url.openConnection();
       }
2. Proxy cannot be initialised with null:

public AnalyticsClientBuilder() {
        proxy = new Proxy(Type.DIRECT, null);
        authBuild = new AuthenticatorBuilder();
        authBuild.setProxy(proxy);
    }

Gives nullpointer exception when a new AnalyticsClientBuilder is created.
1. authBuild.setProxy(proxy); shouldnt be called in the constructor of AnalyticsClientBuilder but when the 'withProxy' methods are called.

**Comment by trekawek** [comment]
Fixed as suggested.
