### ISSUE TITLE
Using this library in a OSGI Context

### ISSUE THREAD

**Issue by ghost** [Adobe-Marketing-Cloud/analytics-java-library#9]
This bundle cannot be used in a OSGI context as it complains of the following dependencies not being in the OSGI bundles maven dependencies:

```
    <dependency>
        <groupId>com.google.android</groupId>
        <artifactId>android</artifactId>
    </dependency>
    <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk15on</artifactId>
    </dependency>
```

which is actually really bad to have an android dependency in an osgi context. Suggest to use another JWT library. As for example: https://bitbucket.org/b_c/jose4j/wiki/Home

**Comment by trekawek** [comment]
I changed the packaging type to bundle and marked android and bouncycastle dependencies as unused (`import !android.util, ...`). Not sure which OSGi container do you use, but now it works on the AEM 6.1.
